# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 785c7931a5a0e76bef31cbd6d1d5ad9b498b1731ee3d7ec7432ac9f6b63ee2216428e259f34bbde4c5228661c4d4b1582cf0acff590250a7a8d376895d7e6f32
  auth_token: a2f0b44e1c17a45b04aaa48d5a786ec8a75bf8cf80e42ff10ef4300fb551f145eac9bd2a316d93de65dc3be6a0d3d049a66d40260e1f20c3126a3914bd4c24f8
  google_auth_client_callback: http://localhost:3000/google-callback

test:
  secret_key_base: 74c9194a330267851e4e6efeab474a9b1a4c098c6b366ffa1e3a42d92f3963a02598310d53e5ed7e63b51e04248cfc421ea86d8cde0dd858e70a7425d6bbd1f5
  auth_token: a2f0b44e1c17a45b04aaa48d5a786ec8a75bf8cf80e42ff10ef4300fb551f145eac9bd2a316d93de65dc3be6a0d3d049a66d40260e1f20c3126a3914bd4c24f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth_token: <%= ENV["AUTH_TOKEN"] %>
  google_auth_client_id: <%= ENV["PUMPKIN_GOOGLE_OAUTH_CLIENT_ID"] %>
  google_auth_client_secret: <%= ENV["PUMPKIN_GOOGLE_OAUTH_CLIENT_SECRET"] %>
  google_auth_client_callback: <%= ENV["PUMPKIN_GOOGLE_OAUTH_CLIENT_CALLBACK"] %>
  google_auth_required_domain: <%= ENV["PUMPKIN_GOOGLE_OAUTH_REQUIRED_DOMAIN"] %>